### ISSUE TITLE
"v" and "V" characters are missing

### ISSUE THREAD

**Issue by ccarcaci** [lmammino/indexed-string-variation#10]
https://github.com/lmammino/indexed-string-variation/blob/2bebc3c8794ac6f270240d8bdd0e2599562f80ac/src/index.js#L7

**Comment by lmammino** [comment]
Lol, that's an embarassing one, but well done on spotting it. Would you like to submit a PR?

**Comment by ccarcaci** [comment]
I don't have the right permission to create a new branch :(

**Comment by lmammino** [comment]
@claudiocarcaci you can fork this repo (using the fork button on the top right corner of this page) and then do the changes in your fork. When you are ready you can submit a PR (pull request) from your fork branch to the master branch here.

This will make so that you will become an official contributor on this official repository (if you'd like that).

if you need a full walkthrough on how to make a contribution to a GitHub repo, checkout [this article](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/).

**Comment by lmammino** [comment]
Hey @claudiocarcaci, let me know if you want to give this a go anytime soon, otherwise, I will make sure to do it as soon as I have a free minute.

**Comment by ccarcaci** [comment]
TY for the advice!
In the afternoon I'll work on it!

**Comment by ccarcaci** [comment]
Done!
I hope that everything is good, its my first PR.
